#!/bin/bash

cmd_l1="$1"
testSetFile="$2"

while read stems; do
        tmp_out=$(mktemp)
	argument=$(cat "${stems}.args")
        "${cmd_l1}" $argument < "${stems}.in" > "$tmp_out"

        diff "$tmp_output" "${stems}.out" > /dev/null

        if [ $? -eq 0 ]; then
                echo "Test ${stems} passed"
        else
                echo "Test ${stems} failed"
                echo "Expected output:"
                cat "${stems}.out"
                echo "Actual output:"
                cat "$tmp_out"
        fi
        rm "$tmp_out"
done < "$testSetFile"
