#!/bin/bash

if [ $# -eq 0 ]; then 
    echo 'Usage ./testDescribe testsetfile' >&2
    exit
fi

while read -r line; do 
    stems=( $line )
    length=$((${#stems[@]}-1))


    for ((i=0;i<=length;i++));do
    value=$($1 < ${stems[i]}.in)
    diff <(echo ${value}) <(echo $(cat ${stems[i]}.out)) > /dev/null
    return_status=$?

    if [[ ${return_status} -eq 0 ]]; then 
        echo "Test ${stems[i]} passed"
    else 
        printf "Test ${stems[i]} failed\n"
        printf "Expected output:\n$(cat ${stems[i]}.out)\n"
        printf "Actual output:\n${value}\n"
    fi
 
    done
done < $2