#!/bin/bash

cmd_l1="$1"
testSetFile="$2"

while read stems; do
	tmp_out=$(mktemp)
	"${cmd_l1}" < "${stems}.in" > "$tmp_out"
	diff "$tmp_out" "${stems}.out" > /dev/null  #redirect ouput into null
	if [ $? -eq 0 ]; then
		echo "Test ${stems} passed"
	else
		echo "Test ${stems} failed"
		echo "Expected output:"
		cat "${stems}.out"
		echo "Actual output:"
		cat "$tmp_out"
	fi
	rm "$tmp_out"
done < "$testSetFile"

