#!/bin/bash

if [ $# -eq 0 ]; then 
    echo "Usage: $0 testSetFile" >&2
    exit
fi
testSetFile="$1"
for stems in $(cat "$testSetFile"); do
	#load descfile0
	desc="${stems}.desc"
	if [ -e "$desc" ]; then
		cat "$desc"
	else
		echo "${stems} No test description"
	fi
done

